# Working with NumPy

### Creating arrays

In [1]:
import numpy as np

a = np.array([11, 12, 13, 14, 15])

In [ ]:
print(a) # values are not comma seperated
         # its also a one dimensional array

[11 12 13 14 15]


In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
b = np.array(100) # zero dimensional array (single value)

print(b)
print(type(b))

100
<class 'numpy.ndarray'>


In [7]:
c = np.array((('a', 'b', 'c'), ('d', 'e', 6))) # tuple of tuples, starting ith both string and int value

print(c) # two dimensional array

[['a' 'b' 'c']
 ['d' 'e' '6']]


In [9]:
d = np.array(((1, 2, None),(3, 4, 5)))

print(d)

[[1 2 None]
 [3 4 5]]


In [ ]:
d = np.array(((1, 2, np.nan),(3, 4, 5))) # NumPy uses NaN

print(d)

[[ 1.  2. nan]
 [ 3.  4.  5.]]


In [ ]:
bess_list = [
    ([(1,2,3)], [(4,5,6)]),
    ([(7,8,9)], [(10,11,12)]),
    ([(13,14,15)], [(16,17,18)])
]

e = np.array(bess_list)

print(e) # four dimensional array

[[[[ 1  2  3]]

  [[ 4  5  6]]]


 [[[ 7  8  9]]

  [[10 11 12]]]


 [[[13 14 15]]

  [[16 17 18]]]]


In [12]:
print(e.ndim) # number of dimensions

4


In [13]:
print(e.size) # number of elements in the array

18


In [ ]:
print(e.shape) # what is the size of each dimension, given as a tuple, listed from the outside in


# bess_list = [
#     ([(1,2,3)], [(4,5,6)]),
#     ([(7,8,9)], [(10,11,12)]),
#     ([(13,14,15)], [(16,17,18)])
# ]
#      List includes 3 items (3 tuples) -- outermost dimension
#      Each tuple in the next layer contains 2 items (2 lists)
#      Each list in the next layer contains 1 item (a tuple)
#      in the innermost tuple, there are 3 elements

(3, 2, 1, 3)


In [15]:
print(e)

[[[[ 1  2  3]]

  [[ 4  5  6]]]


 [[[ 7  8  9]]

  [[10 11 12]]]


 [[[13 14 15]]

  [[16 17 18]]]]


In [16]:
print(e[-1][-1][-1][-1])

18
