# Ex5A NumPy Fundamentals

This exercise introduces arrays, transposing, and working with dimensions

In [1]:
import numpy as np

## Array Basics

In [2]:
fruits = np.array(['apple', 'banana', 'cherry', 'date'])

In [3]:
arr_1 = np.array(fruits)
print(arr_1)

['apple' 'banana' 'cherry' 'date']


In [5]:
print(type(arr_1))
print(arr_1.dtype)

<class 'numpy.ndarray'>
<U6


The letter 'U' mean its a Unicode string array, hold up to six characters.

In [7]:
arr_2 = np.array(((10,11,12),(13,14,15)))
print(arr_2)

[[10 11 12]
 [13 14 15]]


In [8]:
print(arr_2.T)

[[10 13]
 [11 14]
 [12 15]]


In [9]:
print(arr_2)

[[10 11 12]
 [13 14 15]]


.T doesn't permanently changes the array. As you can see after recalling arr_2 it still stays the same

In [10]:
arr_3 = np.array((
    (1,3,5),
    (2,4,6)
))
print(arr_3)

[[1 3 5]
 [2 4 6]]


In [11]:
arr_4 = np.array((
    arr_3[0,2],
    arr_3[1,1]
))
print(arr_4)

[5 4]


In [12]:
arr_5 = np.ones((2,2,2))

print(arr_5)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


arr_5: It is three dimensions because of the three brackets. Each dimension contains 2 values using '1'