# Module 1 Continuing NumPy

## Section 1.A Continuing NumPy

### 1.A.1 Using loops with arrays

- Loops can be used to iterate over one or multiple dimensional arrays.
    - 1 D array, loops through each element one by one
    - N-dimensional arrays...
        - Loop runs against outermost dimension, each nested loop runs against next inner dimension

In [19]:
# Example:
import numpy as np
arr3d = np.array([
    [[8,7], [6,5]], 
    [[4,3], [2,1]], 
    [[9,10],[11,12]]
])

In [20]:
for x in arr3d: #First loop of the outer dim
    print(x)

[[8 7]
 [6 5]]
[[4 3]
 [2 1]]
[[ 9 10]
 [11 12]]


In [21]:
for x in arr3d: # loops into the next inner dim
    for y in x:
        print(y)

[8 7]
[6 5]
[4 3]
[2 1]
[ 9 10]
[11 12]


In [22]:
for x in arr3d: # loops the final inner dimension
    for y in x:
        for z in y:
            print(z)

8
7
6
5
4
3
2
1
9
10
11
12


### 1.A.2 Joining arrays with concatenate()

- In NumPy, arrays are joined on an axis


In [23]:
# Example: Joining two 1D array
arr_a = np.array([1, 2, 3])
arr_b = np.array([4, 5, 6])

arr_c = np.concatenate((arr_a, arr_b))
print(arr_c)


[1 2 3 4 5 6]


In [24]:
# Example: Joining two 2D arrays on axis 1
arr_d = np.array([[1, 2], [3, 4]])
arr_e = np.array([[5, 6], [7, 8]])
arr_f = np.concatenate((arr_d, arr_e), axis=1)
print(arr_f)

[[1 2 5 6]
 [3 4 7 8]]


In [25]:
# Example: Joining using stack()
arr_g = np.array([1, 2, 3])
arr_h = np.array([4, 5, 6])
arr_i = np.stack((arr_g, arr_h))
print(arr_i)

# axis = 1
arr_j = np.stack((arr_g, arr_h), axis=1)
print(arr_j)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [26]:
# using a practical example:

# say I've got 2 sets of exam grades, from a original exam date and then a later makeup for some students who needed it 
exam_score = [.78, .89, .92, .82, .99]
exam_score_makeup = [.90, .85]

exam_all = np.concatenate((np.array(exam_score), np.array(exam_score_makeup)))

In [27]:
project_scores = np.array([.88, .91, .97, .85, .96, .89, .87])

gradebook = np.stack((exam_all, project_scores)) # make sure they have same amount of values
print(gradebook)

[[0.78 0.89 0.92 0.82 0.99 0.9  0.85]
 [0.88 0.91 0.97 0.85 0.96 0.89 0.87]]


### 1.A.3 NaN values

- In NumPy and pandas, "null" values are translated to NaN (not a number)
    - Used as a placeholder for missing data
- NaN is **not** equivalent to None(and neither is equal to zero)
    - **None** means "the value here is set to no value"
    - **NaN** means "the value here is missing"
    - **0** means "the value here is value of zero

### 1.A.4 Stacking helper functions

- Includes helper functions to stack along rows/horizontal, column/vertical, or height/depth


In [28]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

**hstack()** - stack horizontal along column axis

In [29]:
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


**vstack()** - stacks vertically along row axis

In [30]:
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


**dstack()** - stack along height/depth

In [31]:
arr = np.dstack((arr1, arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


### 1.A.5 Splitting arrays

- Splitting breaks one array into multiple
- **array_split()**, passing argument of the array to be split, number of splits, with results as a list of arrays

In [32]:
# Example:
arrA = np.array([1, 2, 3, 4, 5, 6])
arrB = np.array([7,8,9,10,11, 12])

In [33]:
# Example 1: Split into equal size arrays
newarr1 = np.array_split(arr, 3)
print(newarr1)

[array([[[1, 4],
        [2, 5],
        [3, 6]]]), array([], shape=(0, 3, 2), dtype=int64), array([], shape=(0, 3, 2), dtype=int64)]


In [34]:
# Example 2: split does not divide evenly
newarr2 = np.array_split(arr, 4)
print(newarr2)

[array([[[1, 4],
        [2, 5],
        [3, 6]]]), array([], shape=(0, 3, 2), dtype=int64), array([], shape=(0, 3, 2), dtype=int64), array([], shape=(0, 3, 2), dtype=int64)]


#### Using hsplit() / vsplit() / dsplit()

- hsplit() works on the 0 axis, is not forgiving of uneven splits
- vsplit() works on the 1 axis
- dsplit() works on the 2 axis

In [35]:
# hsplit()
print(np.hsplit(arr, 2))

ValueError: array split does not result in an equal division

In [ ]:
# vsplit()
ab = np.stack((arrA, arrB))
print(ab)

print(np.vsplit(ab, 2))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[array([[1, 2, 3, 4, 5, 6]]), array([[ 7,  8,  9, 10, 11, 12]])]


In [47]:
full_year = np.array(([100, 120, 130,140,150,160, 170, 180,190,200,210,220],
                      [200,210,190,205,220,230,240,235,225,215,205,195],
                      [90,95,100,110,115,120,125,130,120,115,110,105]))

In [50]:
quarter = np.array_split(full_year, 4, axis = 1)
print(quarter)

q1, q2, q3, q4 = quarter
print(f"This is the first quarter:\n {q1}")

[array([[100, 120, 130],
       [200, 210, 190],
       [ 90,  95, 100]]), array([[140, 150, 160],
       [205, 220, 230],
       [110, 115, 120]]), array([[170, 180, 190],
       [240, 235, 225],
       [125, 130, 120]]), array([[200, 210, 220],
       [215, 205, 195],
       [115, 110, 105]])]
This is the first quarter:
 [[100 120 130]
 [200 210 190]
 [ 90  95 100]]


### 1.A.6 Using where() to search and alter arrays

- **where()** function is used to retrieve the indices of elements in and N-D array where condition is true.

In [ ]:
# Syntax:
np.where(condition[x, y])

- **x**: specifies a replacement value for first condition
- **y**: provides a replacement when condition was not met

In [ ]:
# Example:
a = np.array([4,9,4,8,0,6])
b = np.where(a < 5)
print(b) # (array([0, 2, 4], dtype=int64),)
print(np.array(b))

(array([0, 2, 4]),)
[[0 2 4]]


In [ ]:
# extra examples:
c = np.where(a < 5, a, a * .9)
print(c)

d = np.where(a < 5, 'little', a)
print(d)

[4.  8.1 4.  7.2 0.  5.4]
['little' '9' 'little' '8' 'little' '6']


In [ ]:
# More examples:
print(np.where(full_year > 200)) # with only a condition, returns the array
print()

print(np.where(full_year > 200, full_year, np.nan)) # lets you set a return value and not-found value


(array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1]), array([10, 11,  1,  3,  4,  5,  6,  7,  8,  9, 10]))

[[ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan 210. 220.]
 [ nan 210.  nan 205. 220. 230. 240. 235. 225. 215. 205.  nan]
 [ nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan  nan]]


In [ ]:
print(full_year[full_year > 200]) # Bracket filtering

[210 220 210 205 220 230 240 235 225 215 205]


In [ ]:
print(full_year[full_year % 3 == 0])

[120 150 180 210 210 240 225 195  90 120 120 105]


In [ ]:
div_by_3 = full_year % 3 == 0
print(full_year[div_by_3])

[120 150 180 210 210 240 225 195  90 120 120 105]


### 1.A.7 Sorting arrays

- .sort() function returns a copy of the array in an ordered sequence
- Using .sort() on multi-dimensional arrays will sort each component array

In [ ]:
# Example: sorting an array of integers
a = np.array([14,9,4,18,0,6])
print(np.sort(a))

[ 0  4  6  9 14 18]


In [ ]:
# Example: sorting an array of strings
b = np.array(['14','9','4','18','0','6'])
print(np.sort(b))

['0' '14' '18' '4' '6' '9']


In [ ]:
# sorting a 3D array
y = np.array([[
    [6,2],
    [6,4],
    [3,1],
    [9,8],
    [9,0],
    [4,2],
    [5,4],
    [8,6]
]])

print(np.sort(y))

[[[2 6]
  [4 6]
  [1 3]
  [8 9]
  [0 9]
  [2 4]
  [4 5]
  [6 8]]]


In [ ]:
# Example from class:
num_x = np.array([(7,6,2,1,9),(5,3,9,1,0)])

In [ ]:
print(np.sort(num_x)) # sort() will return a copy of array that is sorted

[[1 2 6 7 9]
 [0 1 3 5 9]]


In [ ]:
str_x = [('I-1456', 'InstaDerp', '110-XR', '#Zenith', 12, 14, 110, 145, 8)]
str_x = np.array(str_x)
print(str_x)

[['I-1456' 'InstaDerp' '110-XR' '#Zenith' '12' '14' '110' '145' '8']]


In [ ]:
print(np.sort(str_x))

[['#Zenith' '110' '110-XR' '12' '14' '145' '8' 'I-1456' 'InstaDerp']]


### 1.A.8 Filtering arrays

- Arrays can be **filtered** based on a Boolean index list or conditional logic
    - Filtering means retrieving just the values that meet the condition

In [ ]:
a = np.array([14,9,4,18,0,6])

x = a > 10
a_over_10 = a[x]
print(a_over_10)

[14 18]


## Section 1.B Random in NumPy

### 1.B.1 Random Module of NumPy

- It is a **pseudo-random number generator** which can sample on a variety of probability distribution.
- Not suitable for apps requiring true randomness

- Syntax:
    - np.random.[function name]

### 1.B.2 Simple random number functions

- **randint()** generates a random integer
    - Start and stop parameters allow you to specify a range
    - The **size()** parameter is used to specify number of elements by row and column when generating


In [ ]:
# Example:
random_int = np.random.randint(90, 100, size=(2, 5)) # For size: (rows, How many elements in the rows)
print(random_int)

[[98 90 92 90 96]
 [90 94 93 95 93]]


In [ ]:
# Example from class:
some_ints = np.random.randint(100, size = (5)) # assume a zero start == from 0 to 100
print(some_ints)

[40 21 85 10 13]


In [ ]:
more_ints = np.random.randint(100, size = (5, 3))
print(more_ints)

[[ 4 80 30]
 [61 48  1]
 [30 38 35]
 [99 85 64]
 [30 22  3]]


- **rand()** generates a random float between 0 and 1
    - Allows you to specify the shape of the array
    - Does not use start/stop parameter AND size() label
    - array size is specified as: **rand([number rows, number columns])**
        - if only one number is provide, number of rows is default to 1

In [ ]:
# Example:
r_f = np.random.rand(3, 2) # rand(rows, columns)
print(r_f)

[[0.18781937 0.03977006]
 [0.64224035 0.68290463]
 [0.39223219 0.16896156]]


### **1.B.3** Random from array using choice()

- Syntax:
    - np.random.choice()
- The **choice()** method allows you to generate one random value based on a 1D array
    - size = () parameter can be used to specify how many rows and columns an array should have

In [37]:
# Example 1:
a = np.random.choice([3,5,7,9], size =(3, 5))
print(a)

[[9 3 9 7 3]
 [7 9 7 3 5]
 [3 3 5 9 5]]


In [38]:
# Example 2:
b = np.array([414,715,651,612,630])
c= np.random.choice(b, size = (5))
print(f'{c} \n')

d = np.random.choice(b)
print(d)



[612 715 715 612 414] 

715


### 1.B.4 Random distributions

- A **random distribution** is a set of random numbers that follow a certain probability density function
- We can use choice() to generate an array with a random number distribution based on define probability
    - Probability (parameter p = []) can be specified for each value in the array. Parameter must be between 0 and 1, with total of all probability values must equal 1

In [42]:
# Example:
x = np.random.choice(
    ['cat', 'dog', 'bunny', 'snake', 'fish'],
    p = [0.2, 0.1, 0.6, 0.0, 0.1], size = (10))
print(x)

['bunny' 'bunny' 'bunny' 'bunny' 'bunny' 'bunny' 'bunny' 'bunny' 'cat'
 'fish']


### 1.B.5 Normal distribution

- **normal()** to generate a normal data distribution, using three parameters:
    - **loc** - the mean
    - **scale** - standard deviation (spread/width)
    - **size** - the shape of the returned array (array length of rows, columns)

In [43]:
x = np.random.normal(loc = 5, scale = 2, size = (30))
print(x)

[5.91237781 4.43663549 5.13622402 1.69839723 6.04059714 4.94096191
 5.00523787 3.55115683 3.91338985 4.52022777 4.95744965 5.59539209
 8.21854177 5.22212424 6.88129582 4.73098046 4.77569416 2.46968138
 9.26999219 6.20558284 4.34679168 5.64641317 6.91980883 3.67135487
 5.09234492 2.24746282 4.49169649 4.31535116 6.81918996 6.48343649]


## Section 1.C Mathematical Tools in NumPy

### 1.C.1 Permutation of arrays

- A **permutation** is a different arrangement/order of the same set of values
    - For example, [1,2] has only one permutation: [2,1]
    - The more values in a set, the more permutations.
        - e.g. [1,2,3]: has permutation of [1,3,2], [2,1,3], [2,3,1], [3,1,2] and [3,2,1]
- Permutation can be generated using shuffle() or permutation()

In [44]:
# shuffle() changes the order of elements in-place (reorder the array)
h = np.array([1,2,3,4,5])
np.random.shuffle(h)
print(h)

[1 5 2 4 3]


In [46]:
# permutation() returns a new array with the elements in a new random order
i = np.array([1,2,3,4,5])
print(np.random.permutation(i))
print(i)

[2 4 1 5 3]
[1 2 3 4 5]


### 1.C.3 Basic arithmetic with arrays

- Arithmetic functions (requires 2 input args of arrays/list/tuples):
    - **add()** - 1st array values plus second array values
    - **subtract()** - 1st array values minus 2nd array values
    - **multiply()** - 1st array values times 2nd array values
    - **divide()** - 1st array values divided by 2nd array values
    - **power()** - value from 1st array and raised to the power of the values from the 2nd array
    - **mode()** or **remainder()** - returns remainder, when dividing values of 1st array by values of 2nd array

### 1.C.4 Rounding decimal numbers in NumPy

- NumPy offers five main method of roundinf decimals:
    - **trunc()** - returns the number with the decimal place chopped off
    - **fix()** - rounds to the nearest integer toward zero
    - **floor()** - rounds off to the nearest lower integer
    - **ceil()** - rounds off to the nearest higher integer
    - **round()** - *must specify number of decimal places* In **NumPy**'s round(), rounds to the nearest even value

In [51]:
# Example:
x = .123456
y = np.round(x, 4)
print(y)

0.1235


### 1.C.5 Summations in NumPy

- Summation happens over the sequence of elements
- To find the total of all elements in all arrays, use **sum()**

In [57]:
# Example:
a = np.array([1,2,3])
b = np.array([1,2,3])

c = np.sum([a,b], axis = 1)
print(c)

[6 6]


- Cumulative sum, **cumsum()**, find the rolling total of the elements in an array

In [ ]:
# cumsum() example:
d = np.array([1,2,3]) # [x,y,z] --> cumsum([x,y,z]) = [x, x+y, x+y+z]
e = np.cumsum(d)
print(e)

[1 3 6]


### 1.C.6 Products

- To find the product of all elements in an array(s), use **prod()**

In [61]:
# prod() example:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

c = np.prod([a,b], axis = 0)
print(c)

[ 5 12 21 32]


- Use **cumprod()** to find the rolling product of elements

In [65]:
# cumprod() example:
d = np.array([[1,2,3], [4,5,6]])
e = np.cumprod(d)
print(d)
print(e)

[[1 2 3]
 [4 5 6]]
[  1   2   6  24 120 720]


### 1.C.7 Differences

- A discrete difference means subtractiong two successive elements:
    - For [1,2,3,4] the discrete difference would be 2-1, then 3-2 then, 4-3 = [1,1,1]

- To find the difference, use the **diff()** function
- To perform the difference calculation multiple times use the **n=** parameter

In [ ]:
# diff() example:
x = np.array([10,5,20,3]) # diff([a,b,c,x,y,z]) = [b-a, c-b, x-c, y-x, z-y]
y = np.diff(x)
print(y)

[ -5  15 -17]
