# Exercise 1.A NumPy: Manipulating Arrays

In [3]:
import numpy as np

## Looping Through Arrays

In a new code cell, create a variable named arrA as a two-dimensional array
containing (11, 12, 13) and (14, 15, 16) then print arrA.

In [4]:
arrA = np.array([[11,12,13],[14,15,16]])
print(arrA)

[[11 12 13]
 [14 15 16]]


In a new code cell, loop through the first dimension of arrA (i.e. for x in arrA) and
print each element multiplied by 2

In [5]:
for x in arrA:
    print(x * 2)

[22 24 26]
[28 30 32]


In a new code cell, loop through the second dimension of arrA (i.e. for y in x) and
print each element multiplied by 2

In [6]:
for x in arrA:
    for y in x:
        print(y * 2)

22
24
26
28
30
32


In the first loop, it only went to the first dimension, so thats why you can still see the brackets. For the second loop, it went deeper to the second dimension and only displayed the values that was in the first dimension.

Add another code cell. Again loop through the second dimension of arrA (i.e. for y
in x), but this time, assign x*2 to a variable named loop_result. Add another line
of code to print loop_result, then add a comment to the cell to explain how/why
this result is different.

In [12]:
for x in arrA:
    for y in x:
        loop_result = x*2
    
print(loop_result)

# The reason why the results are different, is because x is the accumulating the results but getting overwrited after each iteration

[28 30 32]


## Joining and Stacking Arrays

In [13]:
joined_array_1 = np.concatenate((arrA, arrA), axis=0)
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [17]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [18]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1))
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [ ]:
stacked_array_2 = np.stack((joined_array_1, joined_array_2))
# I had a ValueError. It was an error because the arrays that are being stacked must have the same shape.

ValueError: all input arrays must have the same shape

In [20]:
another_joined_array = np.concatenate((joined_array_1, arrA))
print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [ ]:
another_2 = np.concatenate((joined_array_1, arrA), axis=1)
# ValueError! the input array dimensions axis doesn't match

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

In [27]:
# the control. .stack()
control_stack = np.stack((arrA, arrA))
print(control_stack)

[[[11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]]]


In [ ]:
# hstack()
hstck = np.hstack((arrA, arrA))
print(hstck)
# what this function is doing, is that it takes 2 of arrA and stack them horizontally.

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [ ]:
# vstack()
vstck = np.vstack((arrA,arrA))
print(vstck)
# previously, the two arrA arrays are stacked side by side, this time
# it is stacked vertically. Which means ontop of eachother.

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [25]:
# dstack()
dstck = np.dstack((arrA, arrA))
print(dstck)

[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


## Splitting Arrays

In [36]:
splitsky = np.array_split(joined_array_1, 2)
print(splitsky)
# It printed two arrays. Both still has two dimensions

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [ ]:
spliterino = np.array_split(joined_array_1, 3)
print(spliterino)
# It has split into 3 arrays. All still having two dimensions, but the split was uneven

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


## Searching and replacing Array Values

In [41]:
result_1 = np.where(arrA % 2 == 0, arrA, 'odd')
print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Arrays

In [45]:
arrB = np.array([(7,6), (13,5), (7,3)])
arrB = np.sort(arrB)
print(arrB)

[[ 6  7]
 [ 5 13]
 [ 3  7]]


In [46]:
print(arrB)
z = arrB < 7
arrC = arrB[z]
print(arrC)

[[ 6  7]
 [ 5 13]
 [ 3  7]]
[6 5 3]


In [48]:
print(arrB)
y = arrB >= 7
arrD = arrB[y]
print(arrD)

[[ 6  7]
 [ 5 13]
 [ 3  7]]
[ 7 13  7]
