# Exercise 1.B NumPy Random

In [1]:
import numpy as np

## Generating Random Numbers

Variable name: r_1. Contains a random set of integers between 1 and 20 with a size of 2 elements. Then, print

In [2]:
r_1 = np.random.randint(1, 20, size = (2))
print(r_1)

[ 9 19]


Variable name: r_2. Random number from 1 to 20, with a size of 1 row, 2 columns

In [6]:
r_2 = np.random.randint(1, 20, size = (1, 2))
print(r_2)

[[14  4]]


Created r_3, that contains a random set of floats between 0 and 1 with size of 2 rows, 1 column

In [7]:
r_3 = np.random.rand(2, 1)
print(r_3)

[[0.23035754]
 [0.91708791]]


Create r_4, that contains a random set of integers between 20 and 100 with 4 rows, 5 columns

In [8]:
r_4 = np.random.randint(20, 100, size = (4, 5))
print(r_4)

[[88 89 64 64 58]
 [29 36 31 26 21]
 [41 83 57 75 94]
 [33 91 53 55 90]]


Create r_5, that contains a random set of floats from 0 to 1 with 4 rows / 5 columns

In [9]:
r_5 = np.random.rand(4, 5)
print(r_5)

[[0.2197159  0.95205891 0.56929501 0.87072982 0.23404359]
 [0.02049544 0.87148037 0.03446219 0.79550136 0.44021215]
 [0.62171479 0.2391161  0.37510226 0.67999462 0.46417535]
 [0.776645   0.94902591 0.84339145 0.26540194 0.54954173]]


## Generating Random Choices from an Array

Variable: student, and assign it a 1D array containing the names of 12 of your classmates

In [26]:
students = np.array(['Kevin', 'Brandon', 'Luis', 'Edmund',
                    'Dahlia', 'Destiny', 'Stephanie', 'Natalia',
                    'Jeremiah', 'Hritik', 'John', 'Zack'])

Variable: call_on. Use it to choose one random selection from students, Then, print

In [17]:
call_on = np.random.choice(students)
print(f"The person to start the morning standup will be: {call_on}")

The person to start the morning standup will be: Kevin


Variable: breakout_groups. Use it to choose a random sampling from students that is 3 rows, 4 columns

In [ ]:
breakout_groups = np.random.choice(students, size = (3, 4))
print(breakout_groups)
# This would not be effective in assigning breakout groups, because there are chances of names repeating, making it not useable

[['Luis' 'Brandon' 'Edmund' 'Hritik']
 ['Kevin' 'Kevin' 'Brandon' 'Stephanie']
 ['Dahlia' 'Kevin' 'Natalia' 'Stephanie']]


Variable: call_on_weighted. Make five random selections from students, but this time assign probability values. One student at least has zero liklihood of being selected, and at least one student with 30% chance of being chosen.

In [ ]:
call_on_weighted = np.random.choice(students, size = (5),
                                    p = [.3, .1, .1, .05, .05, .1,
                                         .00, .05, .05, .05, .1, .05])
print(call_on_weighted)

# Kevin has 30% of being selected
# Stephanie has 0% of being selected
# Everyone else has either 10% or 5% of being chosen

['Jeremiah' 'Kevin' 'Destiny' 'Kevin' 'Edmund']


## Generating a Normal Distribution

Variable: bell_curve. Assign it a random distribution for which the mean is 10, scale = 5, and the size = (4, 5)

In [30]:
bell_curve = np.random.normal(loc = 10, scale = 5, size = (4, 5))
print(bell_curve)

[[ 6.15994681  4.32381638 24.05253842 11.38201566  9.86243974]
 [ 9.45933905 10.52280176  7.47701234  5.93966697 23.63787697]
 [12.18820937  7.13009264 -3.41834884  1.07266446 13.10792128]
 [ 4.60007439  1.14722362  7.98356657  7.76112843  8.36435462]]
