# Exercise 1.C Performing operations on arrays

In [1]:
import numpy as np

## Sample Arrays

Create five variables r_1 to r_5 containing random sample arrays

In [2]:
r_1 = np.random.randint(1, 20, size = (2))
r_2 = np.random.randint(1, 20, size = (1, 2))
r_3 = np.random.rand(2, 1)
r_4 = np.random.randint(20, 100, size = (4, 5))
r_5 = np.random.rand(4, 5)


## Permutation

print r_4

In [3]:
print(r_4)

[[94 62 73 66 69]
 [32 76 77 52 43]
 [25 51 59 36 60]
 [28 38 79 55 48]]


shuffle() r_4, then print it

In [5]:
np.random.shuffle(r_4)
print(r_4)

[[32 76 77 52 43]
 [25 51 59 36 60]
 [94 62 73 66 69]
 [28 38 79 55 48]]


Comparing the original r_4 and the shuffled version, many of the elements are in different places. Aside from the last sub array that stayed the same.

Variable: new_shuffle. Assign it the value of a random permutation of r_4. 

In [6]:
new_shuffle = np.random.permutation(r_4)
print(new_shuffle)
print(r_4)

[[25 51 59 36 60]
 [32 76 77 52 43]
 [28 38 79 55 48]
 [94 62 73 66 69]]
[[32 76 77 52 43]
 [25 51 59 36 60]
 [94 62 73 66 69]
 [28 38 79 55 48]]


Permutation created a shuffled copy of r_4 while keeping the original array

## Mathmatical Operations

Print r_1 and r_2 including its shape. Then, print r_1 + r_2 including the shape

In [11]:
print(r_1)
print(r_1.shape)

[17  4]
(2,)


In [12]:
print(r_2)
print(r_2.shape)

[[ 6 19]]
(1, 2)


In [13]:
result_1 = np.add(r_1, r_2)
print(result_1)
print(result_1.shape)

[[23 23]]
(1, 2)


Print r_1 and r_3 with their shapes. Then print r_1 + r_3 with its shape

In [14]:
print(r_1)
print(r_1.shape)

[17  4]
(2,)


In [15]:
print(r_3)
print(r_3.shape)

[[0.87255363]
 [0.34762931]]
(2, 1)


In [16]:
result_2 = np.add(r_1, r_3)
print(result_2)
print(result_2.shape)

[[17.87255363  4.87255363]
 [17.34762931  4.34762931]]
(2, 2)


Do the same for r_2 and r_4

In [17]:
print(r_2)
print(r_2.shape)

[[ 6 19]]
(1, 2)


In [18]:
print(r_4)
print(r_4.shape)

[[32 76 77 52 43]
 [25 51 59 36 60]
 [94 62 73 66 69]
 [28 38 79 55 48]]
(4, 5)


In [19]:
result_3 = np.add(r_2, r_4)
print(result_3)
print(result_3.shape)

ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

The arrays have different shapes, so they could not be added together.

In [21]:
np.add(r_1, r_4)

ValueError: operands could not be broadcast together with shapes (2,) (4,5) 

The shape does not match

In [22]:
np.add(r_2, r_3)
# They work together since they have matching shape

array([[ 6.87255363, 19.87255363],
       [ 6.34762931, 19.34762931]])

Add np.array([1]) to r_4

In [23]:
print(np.add(np.array([1]), r_4))

[[33 77 78 53 44]
 [26 52 60 37 61]
 [95 63 74 67 70]
 [29 39 80 56 49]]


Add np.array([[1]]) to r_4

In [24]:
print(np.add(np.array([[1]]), r_4))

[[33 77 78 53 44]
 [26 52 60 37 61]
 [95 63 74 67 70]
 [29 39 80 56 49]]


Add np.array([1,1,1,1,1]) to r_4

In [25]:
print(np.add(np.array([1,1,1,1,1]), r_4))

[[33 77 78 53 44]
 [26 52 60 37 61]
 [95 63 74 67 70]
 [29 39 80 56 49]]


Add np.array([[1],[1]]) to r_4

In [26]:
print(np.add(np.array([[1],[1]]), r_4))

ValueError: operands could not be broadcast together with shapes (2,1) (4,5) 

Broadcasting lets you add two arrays of different shapes. It will "stretch" the smaller shape to match the larger shape. The smaller shaped array is added onto the larger one. The larger shape array determines the resulting array

## Rounding

In [27]:
# print r_3
print(r_3)

[[0.87255363]
 [0.34762931]]


In [28]:
# Use trunc()
print(np.trunc(r_3))

[[0.]
 [0.]]


In [29]:
# Use fix()
print(np.fix(r_3))

[[0.]
 [0.]]


In [30]:
# Use floor()
print(np.floor(r_3))

[[0.]
 [0.]]


In [31]:
# Use ceil()
print(np.ceil(r_3))

[[1.]
 [1.]]


In [32]:
# Use round(), to 2 decimal places
print(np.round(r_3, 2))

[[0.87]
 [0.35]]


## Cumulative Operations

In [34]:
# print r_4
print(r_4)

[[32 76 77 52 43]
 [25 51 59 36 60]
 [94 62 73 66 69]
 [28 38 79 55 48]]


In [36]:
# the sum of all values in r_4
print(np.sum(r_4))

1123


In [38]:
# Sum of all elements along the 0 axis in r_4
print(np.sum(r_4, axis = 0))

[179 227 288 209 220]


In [40]:
# Now along the 1 axis
print(np.sum(r_4, axis = 1))

[280 231 364 248]


In [41]:
# cumulative sum of values in r_4
print(np.cumsum(r_4))

[  32  108  185  237  280  305  356  415  451  511  605  667  740  806
  875  903  941 1020 1075 1123]


In [42]:
# Now along the 0 axis
print(np.cumsum(r_4, axis = 0))

[[ 32  76  77  52  43]
 [ 57 127 136  88 103]
 [151 189 209 154 172]
 [179 227 288 209 220]]


## Grocery Problem

In [43]:
bag1 = np.array([2, 3, 4, 0])
bag2 = np.array([4, 0, 1, 2])

print(bag1)
print(bag2)

[2 3 4 0]
[4 0 1 2]


In [44]:
total1 = np.sum(bag1)
total2 = np.sum(bag2)

print(f"The first bag contains {total1} items, and the second bag contains {total2} items.")

The first bag contains 9 items, and the second bag contains 7 items.


In [47]:
category_total = np.add(bag1, bag2)
print(category_total)
# [Veg, Fruits, Snacks, Bev]

print(f"There are {category_total[0]} vegetables, {category_total[1]} fruits, {category_total[2]} boxes of snackes, and {category_total[3]} beverages in the two grocery bags")

[6 3 5 2]
There are 6 vegetables, 3 fruits, 5 boxes of snackes, and 2 beverages in the two grocery bags


## Teamwork

In [48]:
# [Monday, Tuesday, Wednesday, Thursday, Friday]
ali_knocks = np.array([5, 4, 6, 4, 2])

In [49]:
ben_knocks = np.array([0, 5, 5, 3, 4])

In [50]:
carla_knocks = np.array([3, 6, 0, 3, 4])

In [51]:
all_knocks = np.array([ali_knocks, ben_knocks, carla_knocks])
print(all_knocks)

[[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [54]:
personal_total = np.sum(all_knocks, axis = 1)
print(personal_total)

group_total = np.sum(all_knocks)
print(group_total)

[21 17 16]
54


In [ ]:
daily_knocks = np.sum(all_knocks, axis = 0) # axis = 0, so it gets monday - friday
print(daily_knocks)

rolling_knocks = np.cumsum(daily_knocks) * 0.5
print(rolling_knocks) # About 27 votes through the week.

[ 8 15 11 10 10]
[ 4.  11.5 17.  22.  27. ]
